Added an option to skip updating flatpak files

diff --git a/update b/update
--- a/update
+++ b/update
@@ -1,5 +1,15 @@
 #!/bin/bash
 # A little update script - Ellie Schaefer - 4/30/2024
+
+server=false
+
+while getopts ":s" option; do
+	case $option in
+		s) server=true ;;
+		\?) echo "Invalid option: -$OPTARG"; usage; exit 1;;
+	esac
+done
+
 echo "Updating DNF Packages"
 sudo dnf update
 if [ $? -ne 0 ]
@@ -7,13 +17,18 @@ then
 	echo "DNF update failed, stopping now." >&2
 	exit 1
 fi
-echo "Updating FlatPak Packages"
-flatpak update -y	# Assume yes
-if [ $? -ne 0 ]
+
+if not "$server"
 then
-	echo "Flatpak update failed, stopping now." >&2
-	exit 1
+	echo "Updating FlatPak Packages"
+	flatpak update -y	# Assume yes
+	if [ $? -ne 0 ]
+	then
+		echo "Flatpak update failed, stopping now." >&2
+		exit 1
+	fi
 fi
+
 echo "Updating Dotfiles..."
 cd ~/Dotfiles
 git pull
@@ -22,6 +37,7 @@ then
 	echo "Dotfile update failed, stopping now." >&2
 	exit 1
 fi
+
 echo "Updating Scripts..."
 cd ~/Scripts
 git pull
